name: 'Charlie Anderson: Director of Photography'
favicon: null
layout_spectrum: 1
typography_spectrum: 0.63593
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#ffffff'
    - '#9e0001'
    - '#373737'
    - '#9b9b9b'
  brandStrength: 0.5
  lightness: 0
  saturation: 1
  rhythmicContrast: 0.5
purpose: []
