name: 'Charlie Anderson: Director of Photography'
favicon: null
layout_spectrum: 0.25117
typography_spectrum: 1
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#010101'
    - '#ffffff'
    - '#2e3339'
    - '#9fbbe0'
    - '#6189c5'
  brandStrength: 0
  lightness: 0
  saturation: 0.5
  rhythmicContrast: 1
purpose: []
