name: 'Charlie Anderson: Director of Photography'
favicon: null
layout_spectrum: 0.247
typography_spectrum: 1
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#282828'
    - '#464646'
    - '#9b9a9b'
    - '#bababa'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 1
  rhythmicContrast: 1
purpose: []
