name: 'Charlie Anderson: Director of Photography'
favicon: null
layout_spectrum: 1
typography_spectrum: 0.63593
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#00000d'
    - '#98725c'
    - '#225170'
    - '#fefdfe'
    - '#e4b49b'
  brandStrength: 0.75
  lightness: 0
  saturation: 1
  rhythmicContrast: 0.5
purpose: []
